name: "Example Server"
port: "1234"
urls:
  local: "http://localhost"
  private: "http://192.168.4.23"
  public: "http://192.168.4.23"
  admin_login: "asdf"
  admin_prefix: "asdf"
  login: ""
  prefix: ""
cookie:
  secret: "asdf="
  user:
    name: "example-server"
    message: "why"
  admin:
    name: "example-server-admin"
    message: "why"
creds:
  admin_username: "asdf"
  admin_password: "asdf"
  api_key: "asdf"
  encryption_key: "asdf"
allow_origins:
  -
# save_files_path: "/home/morphs/SAVE_FILES"
save_files_path: "/Users/morpheous/WORKSPACE/GO/BLANK_SERVER/SAVE_FILES"
bolt:
  path: "/Users/morpheous/WORKSPACE/GO/BLANK_SERVER/SAVE_FILES/bolt.db"
docker:
  name: "private-example-server"
git:
  url: "https://github.com/0187773933/BLANK_SERVER.git"
  ssh_url: "git@github.com:0187773933/BLANK_SERVER.git"
go:
  version: "1.22.2"
  os: "linux"
  arch: "amd64"
log:
  time_zone: "America/New_York"
  log_key: "asdf"
  log_level: "debug"
  bolt_db_path: "/Users/morpheous/WORKSPACE/GO/BLANK_SERVER/SAVE_FILES/log.db"
  encryption_key: "asdf"